services:
  postgresql:
    container_name: pass-in-postgresql
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=pass-in
    volumes:
      - pass_in_postgresql_data:/bitnami/postgresql

volumes:
  pass_in_postgresql_data: