services:
  postgresql:
    container_name: pass-in-postgresql
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=pass-in
    volumes:
      - pass_in_postgresql_data:/bitnami/postgresql
    networks:
      - pass-in
  api:
    container_name: pass-in-api
    build:
      context: ../..
      dockerfile: apps/api/Dockerfile
    depends_on:
      - postgresql
    ports:
      - 3333:3333
    environment:
      - DATABASE_URL=postgresql://docker:docker@postgresql:5432/pass-in
    networks:
      - pass-in
volumes:
  pass_in_postgresql_data:
networks:
  pass-in:
    driver: bridge